const productData = [
    {
         id: 0,
    img: "/images.avif",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 378.0,
    offer: 26,
    stars: 1,
    review: 200,
    category: ["formal"],
    sale: true,
    },
    {
         id: 1,
    img: "/images2.avif",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 678.0,
    offer: 26,
    stars: 3,
    review: 200,
    category: ["formal"],
    sale: false,
    },
    {
         id: 2,
    img: "/images3.avif",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 678.0,
    offer: 26,
    stars: 4,
    review: 200,
    category: ["women"],
    sale: true,
    },
    {
         id: 3,
    img: "/images4.avif",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 678.0,
    offer: 26,
    stars: 4,
    review: 200,
    category: ["formal"],
    sale: false,
    },
    {
         id: 4,
    img: "/images5.avif",
    name: "Adventure Solid Cotton Collared Boys Shirt",
    price: 678.0,
    offer: 26,
    stars: 4,
    review: 200,
    category: ["women"],
    sale: true,
    },
]

export default productData;